.\"/* 
.\" * All rights reserved
.\" * Copyright (c) 2015 SUSE LINUX GmbH, Nuernberg, Germany.
.\" * Authors: Howard Guo
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" */
.\" 
.TH HANA_FIREWALL "8" "23 Oct 2015" "" "Automated SUSE firewall setup for SAP HANA"
.SH NAME
hana\-firewall - Set up SUSE firewall for SAP HANA.

.SH SYNOPSIS
.B hana\-firewall
.RB [ apply " | " unapply " | " status " | " dry-run " | " help ]

.SH DESCRIPTION
hana\-firewall is a utility program that manages system firewall configuration for SAP HANA systems running on this host.

hana\-firewall fully integrates with SUSE firewall,
it creates HANA firewall configuration into a custom firewall script to be used with SUSE firewall,
and delegates firewall administration actions to SUSE firewall service.

The HANA firewall rules are added on top of existing rules defined in SUSE firewall.

.SH OPTIONS
.SS
.TP
.B apply
Generate firewall rules (firewall configuration script) for SAP HANA systems and activate them immediately.
If the system already has a user-made firewall rules script on SUSE firewall, the HANA firewall rules will be added into that script instead of generating a new script.
Please consider to run a dry-run and check the output before runing "apply".

.TP
.B unapply
Remove HANA firewall rules from SUSE firewall configuration and restart SUSE firewall.

.TP
.B status
Report the status of HANA firewall configuration on the syste, exit with code 0 if HANA firewall is fully activated;
if HANA firewall configuration is incomplete or not fully activated, the exit code is 255.

.TP
.B dry-run
Show the HANA firewall rules that will be executed when HANA firewall is applied.

.TP
.B help
Print a summary of command line options.

.SH NOTES
Please feel free to continue using YaST Firewall module to manage SUSE firewall \- including management of zones,
interface-zone assignments, and additional TCP/UDP ports.

HANA firewall rules are added on top of SUSE firewall rules.

You do not need to manually trigger or maintain the automatically generated firewall configuration script.

.SH FILES
hana\-firewall reads all configuration files at the following locations:
.NF
/etc/sysconfig/hana\-firewall
/etc/hana\-firewall.d/*

The automatically generated firewall configuration script is located at:
.NF
/etc/hana\-firewall.d/generated_hana_firewall_script


.SH AUTHOR
.NF
Howard Guo <hguo@suse.com>

